core/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views

urlpatterns = [
    path('', Dashboard, name="index"),
    
    path('errors/', Errors, name="errors"),
    path('errorsdetail/<int:pk>/', ErrorDetail, name="errorsdetail"),

    path('transactions/', Transactions, name="transactions"),
    path('transactionsdetails/<str:pk>/', TransactionDetail, name="transactionsdetails"),

    path('stations/', Stations, name="stations"),
    path('addstation/', AddStation, name="addstation"),
    path('editstation/<int:pk>/', EditStation, name="editstation"),
    path('deletestation/<int:pk>/', DeleteStation, name="deletestation"),

    path('users/', Users, name="users"),
    path('adduser/', AddUser, name="adduser"),
    path('deleteuser/<str:pk>/', DeleteUser, name="deleteuser"),

    path('profile/', Profile, name="profile"),
    path('viewuserprofile/<str:pk>/', ViewUserProfile, name="viewuserprofile"),

    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('notifications/<int:pk>/', NotificationDetailView.as_view(), name='notification_detail'),
    path('notifications/unread/', unread, name='unread'),
    path('notifications/mark-all-as-read/', mark_all_as_read, name='mark_all_as_read'),
    path('notifications/clear-all/', clear_all, name='clear_all'),

    path('manager_feedback_message/', manager_feedback_message, name="manager_feedback_message"),
    path('feeds/<int:id>', feeds, name="feeds"),
    path('close_feed/<int:id>', close_feed, name="close_feed"),
    path('open_feed/<int:id>', open_feed, name="open_feed"),
    path('invite/<int:id>/<int:user_id>', InviteUser, name="invite"),
    # path('terminal_page', terminal_page, name="terminal_page"),
    path('manager_feedback_message_reply/', manager_feedback_message_reply, name="manager_feedback_message_reply"),

    path('manager_feedback/', manager_feedback, name="manager_feedback"),
    path('manager_feedback_save/', manager_feedback_save, name="manager_feedback_save"),

    path('password_change/', views.PasswordChangeView.as_view(
        template_name='auth/password/change-password.html',
        success_url = 'password_change_done'), name='password_change'),

    path('password_change/done/', views.PasswordChangeDoneView.as_view(
        template_name='auth/password/change-password-done.html'), name='password_change_done'),

    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),

    path('password_reset/', views.PasswordResetView.as_view(
             template_name='auth/password/password_reset_form.html',
             subject_template_name='auth/password/password_reset_subject.txt',
             email_template_name='auth/password/password_reset_email.html',
             # success_url='/login/'
         ), name='password_reset'),

    path('password_reset/done/', views.PasswordResetDoneView.as_view(
             template_name='auth/password/password_reset_done.html'
         ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
             template_name='auth/password/password_reset_confirm.html'
         ), name='password_reset_confirm'),

    path('reset/done/', views.PasswordResetCompleteView.as_view(
             template_name='auth/password/password_reset_complete.html'
         ), name='password_reset_complete'),

    path('login/', Login, name="login"),
    path('logout/', Logout, name="logout"),

    path('400/', Error404, name="400"),
    path('500/', Error500, name="500"),
]

station/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'core.views.Error404'
handler500 = 'core.views.Error500'

core/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from .constants import Actions
import datetime
import pytz
from django.db.models.signals import post_save
from django.dispatch import receiver
import json
from django.urls import reverse
from .renderers import *



class UserManager(BaseUserManager):

    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        now = datetime.datetime.now(pytz.utc)
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        user = self._create_user(email, password, True, True, **extra_fields)
        user.save(using=self._db)
        user_type.objects.update_or_create(
            user=user,
            defaults={
                'is_admin': True
            }
        )
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=254, unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    # CUSTOM USER FIELDS
    firstname = models.CharField(max_length=30, blank=True, null=True)
    lastname = models.CharField(max_length=30, blank=True, null=True)
    telephone = models.IntegerField(blank=True, null=True)
    address = models.CharField(max_length=300)
    zipcode = models.IntegerField(blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    region = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=20, blank=True, null=True)
    additional_address = models.CharField(max_length=30, blank=True, null=True)
    picture = models.ImageField(upload_to='images/users', blank=True, null=True, default='images/users/profile-pixs.jpg')
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)
        
    def get_email(self):
        return self.email
        
    def get_fullname(self):
        return str(self.firstname) + " " + str(self.lastname)

    def get_picture_url(self):
        if self.picture and hasattr(self.picture, 'url'):
            return self.picture.url
        else:
            return "/media/images/users/profile-pixs.jpg"

class user_type(models.Model):
    is_admin = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        if self.is_manager == True:
            return User.get_email(self.user) + " - is_manager"
        else:
            return User.get_email(self.user) + " - is_admin"


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('user'), related_name='notifications')
    content_type = models.ForeignKey(
        ContentType,
        models.SET_NULL,
        verbose_name=_('content type'),
        blank=True,
        null=True
    )
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey()
    action = models.PositiveSmallIntegerField(_('action'), choices=Actions.CHOICES)
    text = models.TextField(_('text'), blank=True)
    date = models.DateTimeField(_('date'), auto_now_add=True)
    is_seen = models.BooleanField(_('seen status'), default=False)
    is_read = models.BooleanField(_('read status'), default=False)

    __data = None

    class Meta:
        verbose_name = _('notification')
        verbose_name_plural = _('notifications')
        db_table = 'station_notifications'

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('notification_detail', kwargs={'pk': self.pk})

    @property
    def data(self):
        if self.__data is None:
            self.__data = json.loads(self.text)
        return self.__data

    def render(self):
        renderers = {
            Actions.STATION_COMPLETED: render_station,
            Actions.TRANSACTION_COMPLETED: render_transaction
        }
        renderer_function = renderers[self.action]
        return renderer_function(self)

class Station(models.Model):

    STATION_STATUS = (
            ("pending", "pending"),
            # ("declined", "declined"),
            ("active", "active"),
            ("blocked", "blocked")
        )

    name = models.CharField(max_length=20)
    description = models.CharField(max_length=300)
    address = models.CharField(max_length=300)
    zipcode = models.IntegerField()
    city = models.CharField(max_length=20)
    region = models.CharField(max_length=20)
    country = models.CharField(max_length=20)
    ipaddress = models.CharField(max_length=20)
    macaddress = models.CharField(max_length=20)
    unit_price = models.FloatField(default=0.0)
    status = models.CharField(default="pending", choices=STATION_STATUS, max_length=10)

    def __str__(self):
        return self.name

class TerminalSettings(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('user'), related_name='terminal_settings')
    unit_price = models.FloatField(default=0.0)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + " - " + str(self.unit_price)

class Transaction(models.Model):

    TRANSACTION_STATUS = (
            ("pending", "pending"),
            ("declined", "declined"),
            ("modify", "modify"),
            ("completed", "completed")
        )

    cigarettecounter = models.IntegerField()
    price = models.FloatField(blank=True, null=True)
    videolink = models.URLField()
    status = models.CharField(default="pending" ,choices=TRANSACTION_STATUS, max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    comment = models.TextField()
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "Transaction" + str(self.id)  + " by " + str(self.user)

    @property    
    def get_detail(self):
        return "Transaction" + str(self.id)  + " by " + str(self.user)

    @property    
    def get_picture_url(self):
        return self.user.picture.url

    @property    
    def get_user_email(self):
        return self.user.email
    
    
    def subject_initials(self):
        unit_price = TerminalSettings.objects.last().unit_price

        return float(unit_price) * self.cigarettecounter

    def save(self, *args, **kwargs):
        if not self.price:
            self.price = self.subject_initials()
        super(Transaction, self).save(*args, **kwargs)

class Error(models.Model):

    ERROR_CHOICE = (
            ("unsolved", "unsolved"),
            ("solved", "solved"),
        )

    code = models.CharField(max_length=10)
    description = models.TextField()
    status = models.CharField(default="unsolved", choices=ERROR_CHOICE, max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    equipment = models.CharField(max_length=40)
    file = models.FileField(upload_to="files/error")

    def __str__(self):
        return "Error " + self.code + " from " + str(self.station)

class Solution(models.Model):
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    error = models.ForeignKey(Error, on_delete=models.CASCADE)

    def __str__(self):
        return "Solution for " + str(self.error) + " by " + str(self.user)

# model for a feedback message
class FeedBack(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_closed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Message(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    message_in = models.ForeignKey(FeedBack, on_delete=models.CASCADE)
    feedback_reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.feedback_reply)

class MessagePermission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

core/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from crispy_forms.helper import FormHelper

class StationForm(ModelForm):
	class Meta:
		model = Station
		fields = '__all__'

class UserForm(ModelForm):
	class Meta:
		model = User
		fields = ['firstname', 'lastname', 'email', 'password', 'telephone', 'address', 
		'zipcode', 'city', 'region', 'country', 'additional_address', 'picture']
		widgets = {
			'password': forms.PasswordInput()
		}

class ProfileForm(ModelForm):
	class Meta:
		model = User
		fields = ['firstname', 'lastname', 'telephone', 'address', 
		'zipcode', 'city', 'region', 'country', 'additional_address', 'picture']

class UpdateErrorForm(ModelForm):
	class Meta:
		model = Error
		fields = ['status', 'description']

class UpdateSolutionForm(ModelForm):
	class Meta:
		model = Solution
		fields = ['description']

class UpdateTransactionForm(ModelForm):
	class Meta:
		model = Transaction
		fields = ['comment', 'status']

templates/core/addstation.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'core/mainbars.html' %}
	<div class="main-container">
	<div class="pd-ltr-20">
		<div class="row">
			<div class="col-xl-12 mb-30">
				<form method="POST">
					{% csrf_token %}
						<div class="form-row">
							<div class="form-group col-md-6 mb-0">
								{{ form.name|as_crispy_field }}
							</div>
							<div class="form-group col-md-3 mb-0">
								{{ form.status|as_crispy_field }}
							</div>
							<div class="form-group col-md-3 mb-0">
								{{ form.unit_price|as_crispy_field }}
							</div>
						</div>
						{{ form.description|as_crispy_field }}
						{{ form.address|as_crispy_field }}
						<div class="form-row">
							<div class="form-group col-md-3 mb-0">
								{{ form.zipcode|as_crispy_field }}
							</div>
							<div class="form-group col-md-3 mb-0">
								{{ form.city|as_crispy_field }}
							</div>
							<div class="form-group col-md-3 mb-0">
								{{ form.region|as_crispy_field }}
							</div>
							<div class="form-group col-md-3 mb-0">
								{{ form.country|as_crispy_field }}
							</div>
						</div>
						<div class="form-row">
							<div class="form-group col-md-6 mb-0">
								{{ form.macaddress|as_crispy_field }}
							</div>
							<div class="form-group col-md-6 mb-0">
								{{ form.ipaddress|as_crispy_field }}
							</div>
						</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
		</div>
	</div>
	</div>

	<script src="{% static 'src/scripts/jquery.min.js' %}"></script>
	<script>
		$(document).ready(function(){
			$('select#id_status').prop("disabled", true);
		}).submit(function(){
    $("select#id_status").removeAttr('disabled');
});
	</script>
{% endblock %}

templates/core/adduser.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'core/mainbars.html' %}
<style>
	.select2-search--dropdown {
    display: none;
}
</style>
	<div class="main-container">
				<!-- Form grid Start -->
				<div class="pd-20 card-box mb-30">
					<div class="clearfix mb-30">
						<div class="pull-left">
							<h4 class="text-blue h4">Create a New User</h4>
						</div>
						<div class="pull-right">
							<a href="{% url 'users' %}" class="btn btn-primary btn-sm"><i class="fa fa-people"></i> View Users</a>
						</div>
					</div>
					<form method="POST">
						{% csrf_token %}
						<div class="row">
							<div class="col-md-6 col-sm-12">
								<div class="form-group">
									<input type="text" name="email" placeholder="Email Address" class="form-control">
								</div>
							</div>
							<div class="col-md-6 col-sm-12">
								<div class="form-group">
									<input type="text" name="telephone" placeholder="Telephone" class="form-control">
								</div>
							</div>
							<div class="col-md-4 col-sm-12">
								<div class="form-group">
									<input type="text" name="firstname" placeholder="Firstname" class="form-control">
								</div>
							</div>
							<div class="col-md-4 col-sm-12">
								<div class="form-group">
									<input type="text" name="lastname" placeholder="Lastname" class="form-control">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<select class="custom-select2 form-control" name="usertype" style="width: 100%; height: 38px;">
										<optgroup label="Select User Type">
											<option value="M" name="is_manager">Manager</option>
											<option value="A" name="is_admin">Admin</option>
										</optgroup>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12 col-sm-12">
								<div class="form-group">
									<textarea name="address" placeholder="Address" class="form-control"></textarea>
								</div>
							</div>
							<div class="col-md-3 col-sm-12">
								<div class="form-group">
									<input type="text" name="zipcode" placeholder="Zipcode" class="form-control">
								</div>
							</div>
							<div class="col-md-3 col-sm-12">
								<div class="form-group">
									<input type="text" name="city" placeholder="City" class="form-control">
								</div>
							</div>
							<div class="col-md-3 col-sm-12">
								<div class="form-group">
									<input type="text" name="region" placeholder="Region" class="form-control">
								</div>
							</div>
							<div class="col-md-3 col-sm-12">
								<div class="form-group">
									<input type="text" name="country" placeholder="Country" class="form-control">
								</div>
							</div>
<!-- 							<div class="col-md-12 col-sm-12 mb-20">
								<div class="custom-file">
									<input type="file" class="custom-file-input">
									<label class="custom-file-label">Select User Image</label>
								</div>
							</div> -->
						</div>
						<button type="submit" class="btn btn-primary">Create User</button>
					</form>
				</div>
				<!-- Form grid End -->
	</div>
{% endblock %}

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{{page_title}}</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />

	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/core.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/icon-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'src/plugins/jquery-steps/jquery.steps.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'src/plugins/datatables/css/dataTables.bootstrap4.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'src/plugins/datatables/css/responsive.bootstrap4.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'vendors/styles/style.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />


	<style>
		@font-face { font-family: product-sans; src: url('../../static/vendors/product-sans/Product Sans Regular.ttf'); } 
		h1,h2,h3,h4,h5 {
			font-family: product-sans!important;
		}
		.btn-primary {
			background-color: #0b132b;
			border-color: #0b132b;
			color: white;
		}
		.btn-primary:hover, .btn-primary:active, .btn-primary:focus, .btn-primary:target {
			background-color: #0b132b;
			border-color: #0b132b;
			color: white;
		}
		.btn-primary:not(:disabled):not(.disabled).active, .btn-primary:not(:disabled):not(.disabled):active, .show > .btn-primary.dropdown-toggle {
    color: #fff;
			background-color: #0b132b;
			border-color: #0b132b;
}
	</style>

<!-- 	<script async src="{% static 'https://www.googletagmanager.com/gtag/js?id=UA-119386393-1' %}"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-119386393-1');
	</script>
 --></head>
<body>

	<div class="mobile-menu-overlay"></div>

	{% block content %}
	{% endblock %}

	<script src="{% static 'src/scripts/jquery.min.js' %}"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js"></script>            
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

	{% block js %}{% endblock %}

	<script src="{% static 'vendors/scripts/core.js' %}"></script>
	<script src="{% static 'vendors/scripts/script.min.js' %}"></script>
	<script src="{% static 'vendors/scripts/process.js' %}"></script>
	<script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
	<script src="{% static 'src/plugins/datatables/js/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'src/plugins/datatables/js/dataTables.bootstrap4.min.js' %}"></script>
	<script src="{% static 'src/plugins/datatables/js/dataTables.responsive.min.js' %}"></script>
	<script src="{% static 'src/plugins/datatables/js/responsive.bootstrap4.min.js' %}"></script>
	<script src="{% static 'src/plugins/jquery-steps/jquery.steps.js' %}"></script>
	<script src="{% static 'vendors/scripts/steps-setting.js' %}"></script>
	
</body>
</html>

templates/core/editstation.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'core/mainbars.html' %}
	<div class="main-container">
	<div class="pd-ltr-20">
		<div class="row">
			<div class="col-xl-12 mb-30">
				<form method="POST">
					{% csrf_token %}
						<div class="form-row">
							<div class="form-group col-md-6 mb-0">
								{{ form.name|as_crispy_field }}
							</div>
							<div class="form-group col-md-3 mb-0">
								{{ form.status|as_crispy_field }}
							</div>
							<div class="form-group col-md-3 mb-0">
								{{ form.unit_price|as_crispy_field }}
							</div>
						</div>
						{{ form.description|as_crispy_field }}
						{{ form.address|as_crispy_field }}
						<div class="form-row">
							<div class="form-group col-md-3 mb-0">
								{{ form.zipcode|as_crispy_field }}
							</div>
							<div class="form-group col-md-3 mb-0">
								{{ form.city|as_crispy_field }}
							</div>
							<div class="form-group col-md-3 mb-0">
								{{ form.region|as_crispy_field }}
							</div>
							<div class="form-group col-md-3 mb-0">
								{{ form.country|as_crispy_field }}
							</div>
						</div>
						<div class="form-row">
							<div class="form-group col-md-6 mb-0">
								{{ form.macaddress|as_crispy_field }}
							</div>
							<div class="form-group col-md-6 mb-0">
								{{ form.ipaddress|as_crispy_field }}
							</div>
						</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
		</div>
	</div>
	</div>
{% endblock %}

templates/core/errordetail.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'core/mainbars.html' %}
	<div class="main-container">
		{% include 'core/info_messages.html' %}
	<div class="pd-ltr-20">
		<div class="row">
			<div class="col-xl-12 mb-30">
		<div class="pd-20 card-box mb-30">
		<div class="clearfix mb-20">
			<div class="pull-left">
				<h4 class="text-blue h4">Error Detail for {{errordetail}}</h4>
			</div>
			<div class="pull-right">
				<a href="{% url 'index' %}" class="btn btn-primary btn-sm"><i class="fa fa-arrow-left"></i>&nbsp; Go Back</a>
			</div>
		</div>
			<table class="data-table table nowrap">
				<thead>
					<tr>
						<th>Terminal</th>
						<th>Equipment</th>
						<th>DATE</th>
						<th>STATUS</th>
						<th>FILE</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>{{errordetail.station}}</td>
						<td>{{errordetail.equipment}}</td>
						<td>{{errordetail.created_at}}</td>
						<td>
							{% if errordetail.status == "unsolved" %}
								<span style="padding: 7px 12px;" class="alert alert-danger">UNSOLVED</span>
							{% else %}
								<span style="padding: 7px 12px;" class="alert alert-success">SOLVED</span>
							{% endif %}
						</td>
						<td><a href="/media/{{errordetail.file}}" target="_blank"><i style="font-size: 22px;" class="dw dw-file"></i></a></td>
					</tr><!-- far fa-file-pdf -->
				</tbody>
			</table>
			<div class="col-xl-12 mb-30">
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					    {{ e_form.description|as_crispy_field }}
					    <div class="form-row">
					      <div class="form-group col-md-2 mb-0">
					        {{ e_form.status|as_crispy_field }}
					      </div>
					    </div>
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
		</div>
			</div>
		</div>
	</div>
	</div>
{% endblock %}

templates/core/notification_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
{% include 'core/mainbars.html' %}
<div class="main-container">
	<div class="pd-ltr-20">
		<div class="card-box pd-20 height-100-p mb-30">
			<div class="clearfix mb-20">
				<div class="pull-left">
					<h4 class="text-blue h3">Notifications</h4>
				</div>
			</div>
		</div>		

	  <div class="row justify-content-center">
	    <div class="col-10">
	      <nav aria-label="breadcrumb">
	        <ol class="breadcrumb">
	          <li class="breadcrumb-item">
	            <a href="{% url 'notifications' %}">{% 'Notifications' %}</a>
	          </li>
	          <li class="breadcrumb-item active" aria-current="page">{{ notification.get_action_display }}</li>
	        </ol>
	      </nav>
	      <div class="d-flex justify-content-between align-items-center mb-3">
	        <h2 class="mb-0">{{ notification.get_action_display }}</h2>
	        <a href="" class="btn btn-outline-danger" role="button">{% 'Delete' %}</a>
	      </div>
	      <div class="card">
	        <div class="card-body">

	        </div>
	      </div>
	    </div>
	  </div>
		
		<div class="footer-wrap pd-20 mb-20 card-box">
			Developed by Oyero Habib. You can reach out to me <a href="http://oyerotech.herokuapp.com/">Here</a>.
		</div>
	</div>
</div>

{% endblock %}